import React from 'react'
import Head from 'next/head'


function PageLayout({ children, style }) {
    return (
        <main className={style}>
            <Head>
                <title>Manage Your Team</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href='/icons/team-svgrepo-com.svg' />
            </Head>
            {children}
        </main>
    )
}

export default PageLayout